main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    # Create a test for this blank url
    path("", RedirectView.as_view(url="mice_repository/", permanent=True)),
    path("accounts/", include("django.contrib.auth.urls")),
    path("admin/", admin.site.urls),
    path("breeding_cage/", include("breeding_cage.urls", namespace="breeding_cage")),
    path("mice_popup/", include("mice_popup.urls", namespace="mice_popup")),
    path(
        "mice_repository/", include("mice_repository.urls", namespace="mice_repository")
    ),
    path("mice_requests/", include("mice_requests.urls", namespace="mice_requests")),
    path("projects/", include("projects.urls", namespace="projects")),
    path("stock_cage/", include("stock_cage.urls", namespace="stock_cage")),
    path("strain/", include("strain.urls", namespace="strain")),
    path("system_users/", include("system_users.urls", namespace="system_users")),
    path("wean_pups/", include("wean_pups.urls", namespace="wean_pups")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

strain/urls.py
from django.urls import path

from strain import views

app_name = "strain"

urlpatterns = [
    path("strain_management", views.strain_management, name="strain_management"),
    path("add_strain", views.add_strain, name="add_strain"),
]

strain/models.py
from django.db import models


class Strain(models.Model):
    strain_name = models.CharField(db_column="Strain", primary_key=True, max_length=20)

    def __str__(self):
        return f"{self.strain_name}"

    class Meta:
        managed = True
        db_table = "strain"

strain/forms.py
from django import forms

from strain.models import Strain


class StrainForm(forms.ModelForm):

    strain_name = forms.CharField(
        required=True,
        widget=forms.TextInput(attrs={"class": "form-control"}),
    )

    class Meta:
        model = Strain
        fields = ["strain_name"]
        labels = {"strain_name": "Strain Name"}
        help_texts = {"strain_name": "Enter the name of the strain."}
        error_messages = {
            "strain_name": {
                "unique": "This strain already exists. Please enter a different strain."
            }
        }

strain/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render

from strain.forms import StrainForm


@login_required
def strain_management(request):
    context = {"strains": StrainForm.Meta.model.objects.all()}
    return render(request, "strain_management.html", context)


@login_required
def add_strain(request):
    if request.method == "POST":
        form = StrainForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("strain:strain_management")
    form = StrainForm()
    return render(request, "add_strain.html", {"form": form})

strain/templates/add_strain.html
{% extends 'base_template.html' %}
{% load static %}
{% block title %}Add New Strain{% endblock %}
{% block content %}

    <div class="container mt-5">
        <form method="post">
            {% csrf_token %}
            <div class="mb-1">
                {% for field in form %}
                    <div class="row mb-1">
                        <div class="col-3 d-flex align-items-center">
                            {{ field.label_tag }}
                        </div>
                        <div class="col-9">
                            {{ field }}
                        </div>
                    </div>
                {% endfor %}
            </div>
            <button class="btn btn-success mt-2" type="submit">
                Confirm New Strain
            </button>
        </form>
    </div>

{% endblock %}

strain/templates/strain_management.html
{% extends 'base_template.html' %}
{% load static %}
{% block title %}Strain Management{% endblock %}
{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-12 d-flex justify-content-between">
                <div>Space here for additional information & stats on each strain. Example stats are a count of mice age ranges</div>
                <a href="{% url 'strain:add_strain' %}">
                    <button class="btn btn-primary">Add Strain</button>
                </a>
            </div>
        </div>

        {% for strain in strains %}
            <div class="card my-3">
                <div class="card-body">
                    <h5 class="card-title">{{ strain.strain_name }}</h5>
                    <div class="row">
                        <div class="col-12">
                            <table class="table table-striped table-hover table-bordered mb-0 shadow-sm">
                                <thead class="thead-light">
                                    <tr>
                                        <th>Pups</th>
                                        <th>< 2 months (excl. pups)</th>
                                        <th>2-6 months</th>
                                        <th>6-12 months</th>
                                        <th>12-24 months</th>
                                        <th>24 months+</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td>placeholder</td>
                                        <td>{{ strain.mice.weaned_lt_2_months_old.count }}</td>
                                        <td>{{ strain.mice.between_2_6_months_old.count }}</td>
                                        <td>{{ strain.mice.between_6_12_months_old.count }}</td>
                                        <td>{{ strain.mice.between_12_24_months_old.count }}</td>
                                        <td>{{ strain.mice.over_24_months_old.count }}</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <p class="card-text">{{ strain.description }}</p>
                </div>
            </div>
        {% endfor %}


    </div>

{% endblock %}