breeding_cage/urls.py
from django.urls import path

from breeding_cage import views

app_name = "breeding_cage"

urlpatterns = [
    path(
        "list_breeding_cages",
        views.list_breeding_cages,
        name="list_breeding_cages",
    ),
    path("add_breeding_cage", views.add_breeding_cage, name="add_breeding_cage"),
    path(
        "view_breeding_cage/<str:box_no>",
        views.view_breeding_cage,
        name="view_breeding_cage",
    ),
    path(
        "edit_breeding_cage/<str:box_no>",
        views.edit_breeding_cage,
        name="edit_breeding_cage",
    ),
]

main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    # Create a test for this blank url
    path("", RedirectView.as_view(url="mice_repository/", permanent=True)),
    path("accounts/", include("django.contrib.auth.urls")),
    path("admin/", admin.site.urls),
    path("breeding_cage/", include("breeding_cage.urls", namespace="breeding_cage")),
    path("mice_popup/", include("mice_popup.urls", namespace="mice_popup")),
    path(
        "mice_repository/", include("mice_repository.urls", namespace="mice_repository")
    ),
    path("mice_requests/", include("mice_requests.urls", namespace="mice_requests")),
    path("projects/", include("projects.urls", namespace="projects")),
    path("stock_cage/", include("stock_cage.urls", namespace="stock_cage")),
    path("strain/", include("strain.urls", namespace="strain")),
    path("system_users/", include("system_users.urls", namespace="system_users")),
    path("wean_pups/", include("wean_pups.urls", namespace="wean_pups")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mice_repository/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from mice_repository import views

app_name = "mice_repository"

urlpatterns = [
    path("", views.mice_repository, name="mice_repository"),
    path("mice_repository", views.mice_repository, name="mice_repository"),
    path(
        "add_mouse_to_repository",
        views.add_mouse_to_repository,
        name="add_mouse_to_repository",
    ),
    path(
        "edit_mouse_in_repository/<str:pk>",
        views.edit_mouse_in_repository,
        name="edit_mouse_in_repository",
    ),
    path(
        "show_mouse_comment/<str:pk>",
        views.show_mouse_comment,
        name="show_mouse_comment",
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mice_repository/models.py
from datetime import date, timedelta

from django.core.exceptions import ValidationError
from django.db import models

from main.constants import EARMARK_CHOICES_PAIRED


class CustomManager(models.Manager):

    def get_queryset(self):
        return super().get_queryset()

    def alive(self):
        return self.filter(culled_date__isnull=True)

    def culled(self):
        return self.filter(culled_date__isnull=False)

    # Can't pass an argument to these age range methods because they need to be used in strain_management templates.
    # More flexible implementation might be custom templatetags in common app
    def weaned_lt_2_months_old(self):
        return self.alive().filter(dob__gt=date.today() - timedelta(days=59))

    def between_2_6_months_old(self):
        min_date = date.today() - timedelta(days=179)
        max_date = date.today() - timedelta(days=60)
        return self.alive().filter(dob__range=(min_date, max_date))

    def between_6_12_months_old(self):
        min_date = date.today() - timedelta(days=364)
        max_date = date.today() - timedelta(days=180)
        return self.alive().filter(dob__range=(min_date, max_date))

    def between_12_24_months_old(self):
        min_date = date.today() - timedelta(days=729)
        max_date = date.today() - timedelta(days=365)
        return self.alive().filter(dob__range=(min_date, max_date))

    def over_24_months_old(self):
        return self.alive().filter(dob__lt=date.today() - timedelta(days=730))


class Mouse(models.Model):

    # When you call Mouse.objects, it will redirect to MortalityManager instead of default Manager
    objects = CustomManager()

    strain = models.ForeignKey(
        "strain.Strain",
        on_delete=models.PROTECT,
        blank=False,
        null=False,
        related_name="mice",
    )
    tube = models.IntegerField(db_column="Tube", blank=True, null=True)
    _global_id = models.CharField(
        db_column="Global ID", max_length=20, primary_key=True
    )
    sex = models.CharField(
        db_column="Sex",
        max_length=1,
        default="M",
        choices=[("M", "Male"), ("F", "Female")],
        null=False,
    )
    dob = models.DateField(db_column="Date of Birth", null=False, blank=False)

    cage = models.ForeignKey(
        "common.CageModel",
        on_delete=models.PROTECT,
        null=True,
        blank=True,
        related_name="mice",
    )

    mother = models.ForeignKey(
        "self",
        on_delete=models.PROTECT,
        null=True,
        blank=True,
        related_name="mother_mouse",
    )
    father = models.ForeignKey(
        "self",
        on_delete=models.PROTECT,
        null=True,
        blank=True,
        related_name="father_mouse",
    )

    project = models.ForeignKey(
        "projects.Project",
        on_delete=models.PROTECT,
        null=True,
        blank=True,
        related_name="mice",
    )

    clipped_date = models.DateField(db_column="Clipped Date", null=True, blank=True)
    earmark = models.CharField(
        db_column="Earmark",
        max_length=4,
        default="",
        choices=EARMARK_CHOICES_PAIRED,
        null=False,
    )
    genotyper = models.ForeignKey(
        "system_users.CustomUser", on_delete=models.SET_NULL, null=True, blank=True
    )

    culled_date = models.DateField(db_column="Culled Date", null=True, blank=True)

    """ Add history back in the future. Error across multiple areas """
    # history = HistoricalRecords()

    coat = models.CharField(
        db_column="Coat", max_length=20, null=True, blank=True, default=""
    )

    # Result could be a set of choices?
    result = models.CharField(
        db_column="Result", max_length=20, null=True, blank=True, default=""
    )

    fate = models.CharField(
        db_column="Fate", max_length=40, null=True, blank=True, default=""
    )

    @property
    def age_days(self):
        return (date.today() - self.dob).days

    @property
    def age_months(self):
        return (date.today() - self.dob).days / 30

    def cull(self, culled_date):
        if self.is_culled():
            raise ValidationError("Mouse has already been culled")
        else:
            self.culled_date = culled_date
            self.save()

    # tube can be set manually or is set automatically using strain.mice.count(). tube value then used to set _global_id
    def clean(self):
        super().clean()
        new_tube = self.strain.mice.count()
        if self.tube is None:
            self.tube = new_tube + 1
        if not self._global_id:
            self._global_id = f"{self.strain.strain_name}-{self.tube}"
        try:
            self.validate_unique()
        except ValidationError as e:
            raise ValidationError(e)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

    def is_genotyped(self):
        return self.earmark != ""

    def is_culled(self):
        return self.culled_date is not None

    def __str__(self):
        return f"{self._global_id}"

    class Meta:
        managed = True
        base_manager_name = "objects"
        db_table = "mice"


class MouseComment(models.Model):

    comment_id = models.OneToOneField(
        "mice_repository.Mouse", on_delete=models.CASCADE, primary_key=True
    )

    comment_text = models.CharField(
        db_column="Text", max_length=400, null=True, blank=True, default=""
    )

    def clean(self):
        super().clean()
        if not self.comment_text:
            self.delete()
            raise ValidationError("Comment text is empty, instance deleted")

    def save(self, *args, **kwargs):
        self.clean()
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.comment_id}"

    class Meta:
        managed = True
        db_table = "comment"

mice_repository/forms.py
from django import forms

from common.models import CageModel
from main.constants import EARMARK_CHOICES_PAIRED, SEX_CHOICES
from mice_repository.models import Mouse, MouseComment
from projects.models import Project
from strain.models import Strain
from system_users.models import CustomUser


# Add validation handling for duplicate _global_id here?
# Needed for formset validation. Could do this in the view
class RepositoryMiceForm(forms.ModelForm):

    tube = forms.IntegerField(
        required=False, widget=forms.NumberInput(attrs={"class": "form-control"})
    )

    sex = forms.ChoiceField(
        initial="M",
        required=True,
        choices=SEX_CHOICES,
        widget=forms.Select(attrs={"class": "form-select"}),
    )
    dob = forms.DateField(
        initial=None,
        required=True,
        input_formats=["%Y-%m-%d"],
        widget=forms.DateInput(
            format="%Y-%m-%d", attrs={"type": "date", "class": "form-control"}
        ),
    )
    cage = forms.ModelChoiceField(
        initial=None,
        queryset=CageModel.objects.all(),
        required=False,
        widget=forms.Select(attrs={"class": "form-select"}),
        label="Current Cage",
    )
    clipped_date = forms.DateField(
        initial=None,
        required=False,
        input_formats=["%Y-%m-%d"],
        widget=forms.DateInput(
            format="%Y-%m-%d", attrs={"type": "date", "class": "form-control"}
        ),
    )
    mother = forms.ModelChoiceField(
        initial=None,
        queryset=Mouse.objects.filter(sex="F"),
        required=False,
        widget=forms.Select(attrs={"class": "form-select"}),
    )
    father = forms.ModelChoiceField(
        initial=None,
        queryset=Mouse.objects.filter(sex="M"),
        required=False,
        widget=forms.Select(attrs={"class": "form-select"}),
    )
    project = forms.ModelChoiceField(
        initial="",
        queryset=Project.objects.all(),
        required=False,
        widget=forms.Select(attrs={"class": "form-select"}),
    )
    earmark = forms.ChoiceField(
        initial="",
        required=False,
        choices=EARMARK_CHOICES_PAIRED,
        widget=forms.Select(attrs={"class": "form-select"}),
    )
    genotyper = forms.ModelChoiceField(
        queryset=CustomUser.objects.all(),
        required=False,
        widget=forms.Select(attrs={"class": "form-select"}),
    )
    strain = forms.ModelChoiceField(
        queryset=Strain.objects.all(),
        required=True,
        widget=forms.Select(attrs={"class": "form-select"}),
    )
    coat = forms.CharField(
        initial="",
        required=False,
        widget=forms.TextInput(attrs={"class": "form-control"}),
    )
    result = forms.CharField(
        initial="",
        required=False,
        widget=forms.TextInput(attrs={"class": "form-control"}),
    )
    fate = forms.CharField(
        initial="",
        required=False,
        widget=forms.TextInput(attrs={"class": "form-control"}),
    )
    culled_date = forms.DateField(
        initial=None,
        required=False,
        input_formats=["%Y-%m-%d"],
        widget=forms.DateInput(
            format="%Y-%m-%d", attrs={"type": "date", "class": "form-control"}
        ),
    )

    class Meta:
        model = Mouse
        fields = "__all__"
        exclude = ["_global_id"]


class MouseCommentForm(forms.ModelForm):

    comment_text = forms.CharField(
        widget=forms.Textarea(attrs={"class": "form-control"}),
        max_length=400,
        required=False,
    )

    class Meta:
        model = MouseComment
        fields = ["comment_text"]

mice_repository/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.template import loader
from django.template.response import TemplateResponse

from main.filters import MouseFilter
from mice_repository.forms import MouseCommentForm, RepositoryMiceForm
from mice_repository.models import Mouse, MouseComment


@login_required
def mice_repository(request):
    template = loader.get_template("mice_repository.html")
    repository_mice_qs = MouseFilter.get_filtered_mice(
        Mouse.objects.all().order_by("_global_id"),
        request,
    )
    context = {
        "repository_mice_qs": repository_mice_qs,
        "filter_form": MouseFilter.get_filter_form(repository_mice_qs, request),
    }
    return HttpResponse(template.render(context, request))


@login_required
def add_mouse_to_repository(request):
    if request.method == "POST":
        form = RepositoryMiceForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("mice_repository:mice_repository")
    else:
        form = RepositoryMiceForm()
    return render(request, "add_mouse_to_repository.html", {"form": form})


@login_required
def edit_mouse_in_repository(request, pk):
    mouse = Mouse.objects.get(pk=pk)
    if request.method == "POST":
        form = RepositoryMiceForm(request.POST, instance=mouse)
        if form.is_valid():
            form.save()
            return redirect("mice_repository:mice_repository")
    else:
        form = RepositoryMiceForm(instance=mouse)
    context = {"mouse": mouse, "form": form}
    return TemplateResponse(request, "edit_mouse_in_repository.html", context)


@login_required
def show_mouse_comment(request, pk):
    comment = MouseComment.objects.filter(pk=pk)
    if request.method == "POST":
        form = MouseCommentForm(request.POST, instance=comment.first())
        if form.is_valid():
            form.save()
            # Close comment popup using HTMX on popup window or info panel instead of url redirect
    else:
        if comment.count() == 0:
            form = MouseCommentForm()
        else:
            form = MouseCommentForm(instance=comment.first())
    return render(request, "show_mouse_comment.html", {"form": form})

website/views/mice_repository_views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.template import loader

from website.forms import RepositoryMiceForm
from website.models import Mouse


@login_required
def mice_repository(request):
    mymice = Mouse.objects.all()
    template = loader.get_template("repository/mice_repository.html")
    context = {"mymice": mymice}
    return HttpResponse(template.render(context, request))


@login_required
def add_mouse_to_repository(request):
    if request.method == "POST":
        form = RepositoryMiceForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("repository/add_mouse_to_repository")
    else:
        form = RepositoryMiceForm()
    return render(
        request, "repository/add_mouse_to_repository.html", {"mice_form": form}
    )

mice_repository/templates/add_mouse_to_repository.html
{% extends 'base_template.html' %}
{% load static %}
{% block title %}Add Mouse to Repo{% endblock %}
{% block content %}
    <div class="container p-3">
        <h2 class="my-3">
            Add a Pre-existing Mouse to the Central Repository
        </h2>
        <div class="col-10">
            <ul class="list-group">
                <li class="list-group-item">
                    This page is for adding a mouse that needs to be imported to the MousePilot central repository manually. For example, if the mouse was bred before MousePilot was deployed at the facility, or if the mouse was purchased from a vendor.
                </li>
                <li class="list-group-item">
                    For now, you can only add one mouse at a time. Future plans include functionality to add multiple existing mice at once through a spreadsheet import or batch creation.
                </li>
                <li class="list-group-item">
                    If Tube is left blank, it will be auto-generated based on the total count of mice for that strain. For example, if there are 50 mice in Strain A, the next mouse added to Strain A will have a Tube of 51
                </li>
                <li class="list-group-item list-group-item-warning">
                    This page is <u><b>not</b></u> for moving a mouse from breeding cages to stock cages and you would create duplicate mice by doing so.
                    Use the "Transfer to Stock" functionality found in <a href="{% url 'breeding_cage:list_breeding_cages' %}">Breeding Cages</a> for that purpose.
                </li>
            </ul>
            <a class="btn btn-secondary mt-4" href="{% url 'mice_repository:mice_repository' %}">
                Back to Repository
            </a>
        </div>
    </div>
    <div class="container mt-3" x-data="{ collapsed: true }">
        <p><b>Only Strain, Sex, and Dob are absolutely required</b></p>
        <form method="post">
            {% csrf_token %}
            <div class="mb-1">
                <div class="row mb-1">
                    <div class="col-3 d-flex align-items-center">
                        {{ form.strain.label_tag }}
                    </div>
                    <div class="col-9">
                        {{ form.strain }}
                    </div>
                </div>
                <div class="row mb-1">
                    <div class="col-3 d-flex align-items-center">
                        {{ form.tube.label_tag }}
                    </div>
                    <div class="col-9">
                        {{ form.tube }}
                    </div>
                </div>
                <div class="row mb-1">
                    <div class="col-3 d-flex align-items-center">
                        {{ form.sex.label_tag }}
                    </div>
                    <div class="col-9">
                        {{ form.sex }}
                    </div>
                </div>
                <div class="row mb-1">
                    <div class="col-3 d-flex align-items-center">
                        {{ form.dob.label_tag }}
                    </div>
                    <div class="col-9">
                        {{ form.dob }}
                    </div>
                </div>
                <div x-show="!collapsed" x-transition id="collapse-fields">
                    <div class="row mb-1">
                        <div class="col-3 d-flex align-items-center">
                            {{ form.cage.label_tag }}
                        </div>
                        <div class="col-9">
                            {{ form.cage }}
                        </div>
                    </div>
                    <div class="row mb-1">
                        <div class="col-3 d-flex align-items-center">
                            {{ form.mother.label_tag }}
                        </div>
                        <div class="col-9">
                            {{ form.mother }}
                        </div>
                    </div>
                    <div class="row mb-1">
                        <div class="col-3 d-flex align-items-center">
                            {{ form.father.label_tag }}
                        </div>
                        <div class="col-9">
                            {{ form.father }}
                        </div>
                    </div>
                    <div class="row mb-1">
                        <div class="col-3 d-flex align-items-center">
                            {{ form.project.label_tag }}
                        </div>
                        <div class="col-9">
                            {{ form.project }}
                        </div>
                    </div>
                    <div class="row mb-1">
                        <div class="col-3 d-flex align-items-center">
                            {{ form.clipped_date.label_tag }}
                        </div>
                        <div class="col-9">
                            {{ form.clipped_date }}
                        </div>
                    </div>
                    <div class="row mb-1">
                        <div class="col-3 d-flex align-items-center">
                            {{ form.earmark.label_tag }}
                        </div>
                        <div class="col-9">
                            {{ form.earmark }}
                        </div>
                    </div>
                    <div class="row mb-1">
                        <div class="col-3 d-flex align-items-center">
                            {{ form.genotyper.label_tag }}
                        </div>
                        <div class="col-9">
                            {{ form.genotyper }}
                        </div>
                    </div>
                    <div class="row mb-1">
                        <div class="col-3 d-flex align-items-center">
                            {{ form.coat.label_tag }}
                        </div>
                        <div class="col-9">
                            {{ form.coat }}
                        </div>
                    </div>
                    <div class="row mb-1">
                        <div class="col-3 d-flex align-items-center">
                            {{ form.result.label_tag }}
                        </div>
                        <div class="col-9">
                            {{ form.result }}
                        </div>
                    </div>
                    <div class="row mb-1">
                        <div class="col-3 d-flex align-items-center">
                            {{ form.fate.label_tag }}
                        </div>
                        <div class="col-9">
                            {{ form.fate }}
                        </div>
                    </div>
                    <div class="row mb-1">
                        <div class="col-3 d-flex align-items-center">
                            {{ form.culled_date.label_tag }}
                        </div>
                        <div class="col-9">
                            {{ form.culled_date }}
                        </div>
                    </div>
                </div>
            </div>
            <button class="btn btn-success mt-2" type="submit">
                Confirm Add Mouse
            </button>

        {% comment %} Can make these button a reusable component {% endcomment %}
            <button class="btn btn-secondary mt-2" type="button"
                    x-on:click="collapsed = !collapsed"
                    x-text="collapsed ? 'Show Optional Fields' : 'Hide Optional Fields'">
            </button>
        </form>
    </div>
{% endblock %}

mice_repository/templates/edit_mouse_in_repository.html
{% extends 'base_template.html' %}
{% load static %}
{% block title %}Edit Mouse in Repo{% endblock %}
{% block content %}
    <div class="container p-3">
        <h2 class="my-3">
            Edit a Mouse in the Global Repository
        </h2>
        <div class="col-10">
            <ul class="list-group">
                <li class="list-group-item">
                    This page is for editing a mouse that is already in the MousePilot central repository.
                </li>
                <li class="list-group-item">
                    This page overrides all other methods of editing mice.
                </li>
                <li class="list-group-item list-group-item-warning">
                    <b>There are currently no safeguards to prevent edits that would affect data integrity.</b> For example, the existing mother of a mouse could be set to male or the result of an earclip could be overwritten.
                </li>
            </ul>
            <a class="btn btn-secondary mt-4" href="{% url 'mice_repository:mice_repository' %}">
                Back to Repository
            </a>
        </div>
    </div>
    <div class="container mt-5" x-data="{ collapsed: true }">
        <form method="post">
            {% csrf_token %}
            <div class="mb-1">
                {% for field in form %}
                    <div class="row mb-1">
                        <div class="col-3 d-flex align-items-center">
                            {{ field.label_tag }}
                        </div>
                        <div class="col-9">
                            {{ field }}
                        </div>
                    </div>
                {% endfor %}
            </div>
            <button class="btn btn-success mt-2" type="submit">
                Confirm Edit Mouse
            </button>
            <button class="btn btn-secondary mt-2" type="button">
                Reset data to state on page load - not implemented yet
            </button>
        </form>
    </div>
{% endblock %}

mice_repository/templates/mice_repository.html
{% extends 'base_template.html' %}
{% load static %}
{% load filter_form %}
{% block title %}Mice Repository{% endblock %}
{% block content %}

    <div class="container-fluid">
        <div x-data="{ showForm: true }">
            <a href="{% url 'mice_repository:add_mouse_to_repository' %}" class="btn btn-primary mb-3">Add Pre-existing Mice</a>

        <!-- Toggle button for filter -->
            <button
                class="btn btn-secondary mb-3"
                @click="showForm = !showForm"
                x-text="showForm ? 'Hide Filter' : 'Show Filter'"
            ></button>

            {% render_filter_form filter_form %}
        </div>

        <!-- Mouse table -->
        <div class="container-fluid d-flex">
            <div class="col">
                <table class="table table-striped table-hover table-bordered">
                    <thead class="thead-dark">
                        <tr class="sticky-top">
                            <th scope="col">Global ID</th>
                            <th scope="col">Tube</th>
                            <th scope="col">Earmark</th>
                            <th scope="col">Sex</th>
                            <th scope="col">DoB</th>
                            <th scope="col">Coat</th>
                            <th scope="col">Strain</th>
                            <th scope="col">Mother</th>
                            <th scope="col">Father</th>
                            <th scope="col">Result</th>
                            <th scope="col">Fate</th>
                            <th scope="col">Action</th>
                            {% comment %} A current location would be useful {% endcomment %}
                        </tr>
                    </thead>
                    <tbody>
                        {% for mouse in repository_mice_qs %}
                            <tr>
                                <td>{{ mouse.pk }}</td>
                                <td>{{ mouse.tube }}</td>
                                <td>{{ mouse.earmark }}</td>
                                <td>{{ mouse.sex }}</td>
                                <td>{{ mouse.dob }}</td>
                                <td>{{ mouse.coat }}</td>
                                <td>{{ mouse.strain }}</td>
                                <td>{{ mouse.mother }}</td>
                                <td>{{ mouse.father }}</td>
                                <td>{{ mouse.result }}</td>
                                <td>{{ mouse.fate }}</td>
                                <td class="p-0 align-middle">
                                    <a
                                        href="{% url 'mice_repository:edit_mouse_in_repository' mouse.pk %}"
                                        class="btn btn-sm btn-success" data-bs-toggle="tooltip" data-bs-html="true" data-bs-placement="top" title="Edit Mouse">
                                        E
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

mice_repository/templates/show_mouse_comment.html
{{ form }}