breeding_cage/urls.py
from django.urls import path

from breeding_cage import views

app_name = "breeding_cage"

urlpatterns = [
    path(
        "list_breeding_cages",
        views.list_breeding_cages,
        name="list_breeding_cages",
    ),
    path("add_breeding_cage", views.add_breeding_cage, name="add_breeding_cage"),
    path(
        "view_breeding_cage/<str:box_no>",
        views.view_breeding_cage,
        name="view_breeding_cage",
    ),
    path(
        "edit_breeding_cage/<str:box_no>",
        views.edit_breeding_cage,
        name="edit_breeding_cage",
    ),
]

main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    # Create a test for this blank url
    path("", RedirectView.as_view(url="mice_repository/", permanent=True)),
    path("accounts/", include("django.contrib.auth.urls")),
    path("admin/", admin.site.urls),
    path("breeding_cage/", include("breeding_cage.urls", namespace="breeding_cage")),
    path("mice_popup/", include("mice_popup.urls", namespace="mice_popup")),
    path(
        "mice_repository/", include("mice_repository.urls", namespace="mice_repository")
    ),
    path("mice_requests/", include("mice_requests.urls", namespace="mice_requests")),
    path("projects/", include("projects.urls", namespace="projects")),
    path("stock_cage/", include("stock_cage.urls", namespace="stock_cage")),
    path("strain/", include("strain.urls", namespace="strain")),
    path("system_users/", include("system_users.urls", namespace="system_users")),
    path("wean_pups/", include("wean_pups.urls", namespace="wean_pups")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

wean_pups/urls.py
from django.urls import path

from wean_pups.views import PupsToStockCageView

app_name = "wean_pups"

urlpatterns = [
    path(
        "pups_to_stock_cage/<str:box_no>",
        PupsToStockCageView.as_view(),
        name="pups_to_stock_cage",
    ),
]

breeding_cage/models.py
from django.db import models

from common.models import CageModel

# Need to track whether female is pregnant


class BreedingCage(CageModel):
    """Could benefit from tracking when the breeding pair was put in the cage"""

    strain = models.ForeignKey(
        "strain.Strain",
        on_delete=models.PROTECT,
        null=False,
        blank=False,
        default="",
    )
    mother = models.ForeignKey(
        "mice_repository.Mouse",
        on_delete=models.PROTECT,
        null=False,
        blank=False,
        related_name="cage_mother",
    )
    father = models.ForeignKey(
        "mice_repository.Mouse",
        on_delete=models.PROTECT,
        null=False,
        blank=False,
        related_name="cage_father",
    )
    date_born = models.DateField(db_column="DBorn", null=True, blank=True, default=None)
    number_born = models.IntegerField(
        db_column="NBorn", null=True, blank=True, default=0
    )
    cull_to = models.CharField(
        db_column="C/To", max_length=20, null=True, blank=True, default=""
    )
    date_wean = models.DateField(db_column="Dwean", null=True, blank=True, default=None)
    number_wean = models.CharField(
        db_column="Nwean", max_length=5, null=True, blank=True, default=""
    )
    pwl = models.CharField(
        db_column="PWL", max_length=5, null=True, blank=True, default=""
    )
    male_pups = models.IntegerField(
        db_column="Male Pups", null=True, blank=True, default=0
    )
    female_pups = models.IntegerField(
        db_column="Female Pups", null=True, blank=True, default=0
    )
    transferred_to_stock = models.BooleanField(
        db_column="Moved to Stock", default=False
    )

    # Used to define immutable values for PupsToStockCageFormSet in wean_pups app
    def get_initial_data_for_pups(self):
        initial_data = []
        for sex, count in [("M", self.male_pups), ("F", self.female_pups)]:
            initial_data += [
                {
                    "sex": sex,
                    "strain": self.strain,
                    "mother": self.mother,
                    "father": self.father,
                    "dob": self.date_born,
                }
                for _ in range(count)
            ]
        return initial_data

    class Meta:
        managed = True
        db_table = "breedingcage"

breeding_cage/forms.py
from django import forms

from breeding_cage.models import BreedingCage
from mice_repository.models import Mouse
from strain.models import Strain


class BreedingCageForm(forms.ModelForm):

    box_no = forms.CharField(
        widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "---"}),
        required=True,
        label="Box Number",
    )
    strain = forms.ModelChoiceField(
        queryset=Strain.objects.all(),
        required=True,
        widget=forms.Select(attrs={"class": "form-select", "placeholder": "Strain"}),
        label="Pup Strain",
    )
    mother = forms.ModelChoiceField(
        queryset=Mouse.objects.filter(sex="F"),
        required=True,
        widget=forms.Select(attrs={"class": "form-select", "placeholder": "Mother ID"}),
    )
    father = forms.ModelChoiceField(
        queryset=Mouse.objects.filter(sex="M"),
        required=True,
        widget=forms.Select(attrs={"class": "form-select", "placeholder": "Father ID"}),
    )
    date_born = forms.DateField(
        initial=None,
        required=False,
        input_formats=["%Y-%m-%d"],
        widget=forms.DateInput(
            format="%Y-%m-%d", attrs={"class": "form-control", "type": "date"}
        ),
        label="DBorn",
    )
    number_born = forms.CharField(
        initial="0",
        required=False,
        widget=forms.TextInput(attrs={"class": "form-control"}),
        label="NBorn",
    )
    cull_to = forms.CharField(
        initial="",
        required=False,
        widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "C/To"}),
        label="C/To",
    )
    date_wean = forms.DateField(
        initial=None,
        required=False,
        input_formats=["%Y-%m-%d"],
        widget=forms.DateInput(
            format="%Y-%m-%d", attrs={"class": "form-control", "type": "date"}
        ),
        label="DWean",
    )
    number_wean = forms.CharField(
        initial="",
        required=False,
        widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "NWean"}),
        label="NWean",
    )
    pwl = forms.CharField(
        initial="",
        required=False,
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "NBorn - NWean"}
        ),
        label="PWL",
    )
    male_pups = forms.IntegerField(
        initial="0",
        required=False,
        widget=forms.TextInput(attrs={"class": "form-control"}),
        label="Current Male Pups",
    )
    female_pups = forms.CharField(
        initial="0",
        required=False,
        widget=forms.TextInput(attrs={"class": "form-control"}),
        label="Current Female Pups",
    )

    class Meta:
        model = BreedingCage
        fields = "__all__"
        exclude = ["transferred_to_stock", "id"]


class PupsToStockCageForm(forms.ModelForm):
    transferred_to_stock = forms.BooleanField(
        required=False, widget=forms.CheckboxInput(attrs={"class": "form-check-input"})
    )

    class Meta:
        model = Mouse
        fields = "__all__"
        exclude = []

website/forms/breeding_cage_forms.py
from django import forms

from website.models import BreedingCage, Mouse


class BreedingCageForm(forms.ModelForm):

    box_no = forms.CharField(
        widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "---"}),
        required=True,
        label="Box Number",
    )
    mother = forms.ModelChoiceField(
        queryset=Mouse.objects.filter(sex="F"),
        required=True,
        widget=forms.Select(attrs={"class": "form-select", "placeholder": "Mother ID"}),
    )
    father = forms.ModelChoiceField(
        queryset=Mouse.objects.filter(sex="M"),
        required=True,
        widget=forms.Select(attrs={"class": "form-select", "placeholder": "Father ID"}),
    )
    date_born = forms.DateField(
        initial=None,
        required=False,
        input_formats=["%Y-%m-%d"],
        widget=forms.DateInput(
            format="%Y-%m-%d", attrs={"class": "form-control", "type": "date"}
        ),
        label="DBorn",
    )
    number_born = forms.CharField(
        initial="0",
        required=False,
        widget=forms.TextInput(attrs={"class": "form-control"}),
        label="NBorn",
    )
    cull_to = forms.CharField(
        initial="",
        required=False,
        widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "C/To"}),
        label="C/To",
    )
    date_wean = forms.DateField(
        initial=None,
        required=False,
        input_formats=["%Y-%m-%d"],
        widget=forms.DateInput(
            format="%Y-%m-%d", attrs={"class": "form-control", "type": "date"}
        ),
        label="DWean",
    )
    number_wean = forms.CharField(
        initial="",
        required=False,
        widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "NWean"}),
        label="NWean",
    )
    pwl = forms.CharField(
        initial="",
        required=False,
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "NBorn - NWean"}
        ),
        label="PWL",
    )
    male_pups = forms.IntegerField(
        initial="0",
        required=False,
        widget=forms.TextInput(attrs={"class": "form-control"}),
        label="Current Male Pups",
    )
    female_pups = forms.CharField(
        initial="0",
        required=False,
        widget=forms.TextInput(attrs={"class": "form-control"}),
        label="Current Female Pups",
    )

    class Meta:
        model = BreedingCage
        fields = "__all__"
        exclude = ["transferred_to_stock"]

breeding_cage/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.template import loader

from breeding_cage.forms import BreedingCageForm
from breeding_cage.models import BreedingCage


@login_required
def list_breeding_cages(request):
    mycages = BreedingCage.objects.all()
    template = loader.get_template("list_breeding_cages.html")
    context = {"mycages": mycages}
    return HttpResponse(template.render(context, request))


@login_required
def view_breeding_cage(request, box_no):
    mycage = BreedingCage.objects.get(box_no=box_no)
    template = loader.get_template("view_breeding_cage.html")
    context = {
        "mycage": mycage,
    }

    return HttpResponse(template.render(context, request))


@login_required
def add_breeding_cage(request):
    if request.method == "POST":
        form = BreedingCageForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("breeding_cage:list_breeding_cages")
    else:
        form = BreedingCageForm()
    return render(request, "add_breeding_cage.html", {"form": form})


@login_required
def edit_breeding_cage(request, box_no):
    cage = BreedingCage.objects.get(box_no=box_no)
    if request.method == "POST":
        form = BreedingCageForm(request.POST, instance=cage)
        if form.is_valid():
            form.save()
            return redirect("breeding_cage:list_breeding_cages")
    else:
        form = BreedingCageForm(instance=cage)
    return render(request, "edit_breeding_cage.html", {"form": form})

website/views/breeding_cage_views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.template import loader

from website.forms import BreedingCageForm
from website.models import BreedingCage


@login_required
def list_breeding_cages(request):
    mycages = BreedingCage.objects.all()
    template = loader.get_template("breeding_cages/list_breeding_cages.html")
    context = {"mycages": mycages}
    return HttpResponse(template.render(context, request))


@login_required
def view_breeding_cage(request, box_no):
    mycage = BreedingCage.objects.get(box_no=box_no)
    template = loader.get_template("breeding_cages/view_breeding_cage.html")
    context = {
        "mycage": mycage,
    }

    return HttpResponse(template.render(context, request))


@login_required
def add_breeding_cage(request):
    if request.method == "POST":
        form = BreedingCageForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("list_breeding_cages")
    else:
        form = BreedingCageForm()
    return render(request, "breeding_cages/add_breeding_cage.html", {"form": form})


@login_required
def edit_breeding_cage(request, box_no):
    cage = BreedingCage.objects.get(box_no=box_no)
    if request.method == "POST":
        form = BreedingCageForm(request.POST, instance=cage)
        if form.is_valid():
            form.save()
            return redirect("list_breeding_cages")
    else:
        form = BreedingCageForm(instance=cage)
    return render(request, "breeding_cages/edit_breeding_cage.html", {"form": form})

breeding_cage/templates/add_breeding_cage.html
{% extends 'base_template.html' %}
{% load static %}
{% block title %}Create Breeding Pair{% endblock %}
{% block content %}

    <div class="container p-3">
        <h2 class="my-3">
            Add a Breeding Cage
        </h2>
        <div class="col-10">
            <ul class="list-group">
                <li class="list-group-item">
                    This page is for adding a new breeding pair or an existing breeding cage that needs to be imported manually.
                </li>
                <li class="list-group-item">
                    It will make a new breeding cage labelled with the Box Number.
                </li>
                <li class="list-group-item">
                    Fields can be updated later as pups are born, sexed, or lost.
                </li>
            </ul>
            <button class="btn btn-secondary ml-auto mt-4">
                <a href="{% url 'breeding_cage:list_breeding_cages' %}" class="text-decoration-none text-white">
                    Back to Breeding Cages
                </a>
            </button>
        </div>
    </div>

    <div class="container mt-3" x-data="{ collapsed: true }">
        <p><b>Only Box Number, Pup Strain, Mother, and Father are absolutely required</b></p>
        <form method="post">
            {% csrf_token %}
            <div class="mb-1">

                <div class="row mb-1">
                    <div class="col-3 d-flex align-items-center">
                        {{ form.box_no.label_tag }}
                    </div>
                    <div class="col-9">
                        {{ form.box_no }}
                    </div>
                </div>
                <div class="row mb-1">
                    <div class="col-3 d-flex align-items-center">
                        {{ form.strain.label_tag }}
                    </div>
                    <div class="col-9">
                        {{ form.strain }}
                    </div>
                </div>
                <div class="row mb-1">
                    <div class="col-3 d-flex align-items-center">
                        {{ form.mother.label_tag }}
                    </div>
                    <div class="col-9">
                        {{ form.mother }}
                    </div>
                </div>
                <div class="row mb-1">
                    <div class="col-3 d-flex align-items-center">
                        {{ form.father.label_tag }}
                    </div>
                    <div class="col-9">
                        {{ form.father }}
                    </div>
                </div>
                <div x-show="!collapsed" x-transition id=collapse-fields>
                    <div class="row mb-1">
                        <div class="col-3 d-flex align-items-center">
                            {{ form.date_born.label_tag }}
                        </div>
                        <div class="col-9">
                            {{ form.date_born }}
                        </div>
                    </div>
                    <div class="row mb-1">
                        <div class="col-3 d-flex align-items-center">
                            {{ form.number_born.label_tag }}
                        </div>
                        <div class="col-9">
                            {{ form.number_born }}
                        </div>
                    </div>
                    <div class="row mb-1">
                        <div class="col-3 d-flex align-items-center">
                            {{ form.cull_to.label_tag }}
                        </div>
                        <div class="col-9">
                            {{ form.cull_to }}
                        </div>
                    </div>
                    <div class="row mb-1">
                        <div class="col-3 d-flex align-items-center">
                            {{ form.date_wean.label_tag }}
                        </div>
                        <div class="col-9">
                            {{ form.date_wean }}
                        </div>
                    </div>
                    <div class="row mb-1">
                        <div class="col-3 d-flex align-items-center">
                            {{ form.number_wean.label_tag }}
                        </div>
                        <div class="col-9">
                            {{ form.number_wean }}
                        </div>
                    </div>
                    <div class="row mb-1">
                        <div class="col-3 d-flex align-items-center">
                            {{ form.pwl.label_tag }}
                        </div>
                        <div class="col-9">
                            {{ form.pwl }}
                        </div>
                    </div>
                    <div class="row mb-1">
                        <div class="col-3 d-flex align-items-center">
                            {{ form.male_pups.label_tag }}
                        </div>
                        <div class="col-9">
                            {{ form.male_pups }}
                        </div>
                    </div>
                    <div class="row mb-1">
                        <div class="col-3 d-flex align-items-center">
                            {{ form.female_pups.label_tag }}
                        </div>
                        <div class="col-9">
                            {{ form.female_pups }}
                        </div>
                    </div>
                </div>
            </div>
            <button class="btn btn-success mt-2" type="submit">
                Confirm Breeding Cage
            </button>
            <button class="btn btn-secondary mt-2" type="button"
                    x-on:click="collapsed = !collapsed"
                    x-text="collapsed ? 'Show extra fields' : 'Hide extra fields'">
            </button>
        </form>
    </div>
{% endblock %}

breeding_cage/templates/edit_breeding_cage.html
{% extends 'base_template.html' %}
{% load static %}
{% block title %}Edit Breeding Cage{% endblock %}
{% block content %}

    <div class="container p-3">
        <h2 class="my-3">
            Edit Breeding Cage
        </h2>
        <div class="col-10">
            <ul class="list-group">
                <li class="list-group-item">
                    This page is for editing an existing breeding cage to reflect changes such as sexing, weaning, or death of pups.
                </li>
            </ul>
            <button class="btn btn-secondary ml-auto mt-4">
                <a href="{% url 'breeding_cage:list_breeding_cages' %}" class="text-decoration-none text-white">
                    Back to Breeding Cages
                </a>
            </button>
        </div>
    </div>

    <div class="container mt-5">
        <form method="post">
            {% csrf_token %}
            <div class="mb-1">
                {% for field in form %}
                    <div class="row mb-1">
                        <div class="col-3 d-flex align-items-center">
                            {{ field.label_tag }}
                        </div>
                        <div class="col-9">
                            {{ field }}
                        </div>
                    </div>
                {% endfor %}
            </div>
            <button class="btn btn-success mt-2" type="submit">
                Confirm Edit
            </button>
        </form>
    </div>
{% endblock %}

breeding_cage/templates/list_breeding_cages.html
{% extends 'base_template.html' %}
{% load static %}
{% block title %}Breeding Cages{% endblock %}
{% block content %}
    <div class="container-fluid">

    <!-- Header and buttons -->
        <div class="row">
            <div class="col-md-12 d-flex justify-content-between " >
                <h1 class="project-header-text">Breeding Cage List</h1>
                <div>
                    <a href="{% url 'breeding_cage:add_breeding_cage' %}" class="btn btn-primary">Add Breeding Cage</a>
                </div>
            </div>
        </div>

    <!-- Show breeding cages -->
        <div class="row">
            {% for cage in mycages %}
                {% if not cage.transferred_to_stock %}
                    <div class="col">
                        <div class="container position-relative card card-body square-cage mb-4 shadow-sm p-0">

                            <h5 class="card-header bg-primary  d-flex justify-content-between">
                                <a class="text-white" href="{% url 'breeding_cage:view_breeding_cage' cage.box_no %}"
                                   data-bs-toggle="tooltip" data-bs-html="true" data-bs-placement="top" title="View Cage">{{ cage.box_no }}</a>
                                <a class="text-decoration-none" href="{% url 'breeding_cage:edit_breeding_cage' cage.box_no %}">
                                    <img src="{% static '/media/white_edit_pen.svg' %}" alt="Edit details" style="height: 1em;"
                                         data-bs-toggle="tooltip" data-bs-html="true" data-bs-placement="top" title="Edit Cage">
                                </a>
                            </h5>

                            <div class="position-absolute bottom-0 w-100 p-2">
                                <div class="d-flex">
                                    {% for i in cage.male_pups|add:"0"|ljust:cage.male_pups %}
                                        <img src="{% static '/media/male_mouse.svg' %}" alt="male_mouse" style="height: 1em;"
                                             data-bs-toggle="tooltip" data-bs-html="true" data-bs-placement="top" title="Male Pup">
                                    {% endfor %}
                                </div>
                                <div class="d-flex">
                                    {% for i in cage.female_pups|add:"0"|ljust:cage.female_pups %}
                                        <img src="{% static '/media/female_mouse.svg' %}" alt="female_mouse" style="height: 1em;"
                                             data-bs-toggle="tooltip" data-bs-html="true" data-bs-placement="top" title="Female Pup">
                                    {% endfor %}
                                </div>
                            </div>

                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>

    </div>
{% endblock %}

breeding_cage/templates/view_breeding_cage.html
{% extends 'base_template.html' %} {% load static %}
{% block title %}View Breeding Cages{% endblock %}
{% block content %}

    <div class="container">
        <div class="d-flex align-items-center justify-content-start overflow-auto">
            <h1 class="h4">Cage Number: {{ mycage.box_no }}</h1>
        </div>
        <table class="table">
            <tbody>
                <tr>
                    <td>Male ID:</td>
                    <td>{{ mycage.father }}</td>
                    <td>Dwean:</td>
                    <td>{{ mycage.date_wean }}</td>
                </tr>
                <tr>
                    <td>Female ID:</td>
                    <td>{{ mycage.mother }}</td>
                    <td>Nwean:</td>
                    <td>{{ mycage.number_wean }}</td>
                </tr>
                <tr>
                    <td>Dborn:</td>
                    <td>{{ mycage.date_born }}</td>
                    <td>C/To:</td>
                    <td>{{ mycage.cull_to }}</td>
                </tr>
                <tr>
                    <td></td>
                    <td></td>
                    <td>Nborn:</td>
                    <td>{{ mycage.number_born }}</td>
                </tr>
                <tr>
                    <td></td>
                    <td></td>
                    <td>PWL:</td>
                    <td>{{ mycage.pwl }}</td>
                </tr>
                <tbody>
                </table>

                <div class="d-flex justify-content-around">
                    <button class="btn btn-primary">
                        <a href="{% url 'breeding_cage:edit_breeding_cage' mycage.box_no %}" class="text-decoration-none text-white">
                            Edit Cage
                        </a>
                    </button>
                    <button class="btn btn-primary">
                        <a href="{% url 'wean_pups:pups_to_stock_cage' mycage.box_no %}" class="text-decoration-none text-white">
                            Transfer to Stock
                        </a>
                    </button>

                    <button class="btn btn-secondary">
                        <a href="{% url 'breeding_cage:list_breeding_cages' %}" class="text-decoration-none text-white">
                            Back to Breeding Cages
                        </a>
                    </button>

                </div>
                <p>For now there are some temporary fields you need to manually edit on a breeding cage to successfully Transfer to Stock: Current Male Pups and Current Female Pups. These values can be changed by the Edit Cage button. Will switch how the final male and female pup count before transfer is calculated to use the correct attribute in the future, but couldn't remember if it was Nwean or PWL. Still unsure what all the breeding cage and stock cage values mean and how they relate to each other.</p>

            </div>
{% endblock %}